version: '3.9'

services:
    postgres:
        image: postgres
        container_name: postgres1_container
        restart: on-failure
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_MULTIPLE_DATABASES=movie_db,message_db
        networks: 
            - main
        ports: 
            - "5432:5432"
        volumes: 
            - ./create_database.sh:/docker-entrypoint-initdb.d/create_database.sql
            - postgres_data:/var/lib/postgresql/data 
            
    pgbackups:
        image: prodrigestivill/postgres-backup-local
        container_name: pgdump
        restart: always
        user: postgres:postgres # Optional: see below
        volumes:
            - ./data/backups:/backups
        links:
            - postgres
        depends_on:
            - postgres
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
         #  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
            - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
            - SCHEDULE=@daily
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=6
            - HEALTHCHECK_PORT=8080
            
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: on-failure
        environment:
            - PGADMIN_DEFAULT_EMAIL=a@a.com
            - PGADMIN_DEFAULT_PASSWORD=a
        ports:
            - "5050:80"
        volumes: 
            - ./data/pgadmin:/var/lib/pgadmin /data
         networks: 
            - main
            
    redis:
        image: redis
        container_name: redis_container
        command: redis-server --requirepass "admin"
        ports: 
            - "6379:6379"
        networks: 
            - main
        restart: on-failure
        volumes:
            - redisdata:/data
            
            
    app:
        container_name: app
        build: .
        command: sh -c "
                    python manage.py makemigrations &&
                    python manage.py migrate --database=movie_db && 
                    python manage.py migrate --database=message_db && 
                    python manage.py collectstatic --no-input && 
                    python manage.py initadmin && 
                    gunicorn -k gevent config.wsgi:application -b 0.0.0.0:8000"
        restart: on-failure
        depends_on: 
            - postgres
            - redis
        expose: 
            - "8000"
        networks:
            - main
        volumes: 
            - .:/code/
            - ./static:/app/static
            - ./media:/app/media

        
    nginx:
        container_name: nginx
        command: nginx -g 'daemon off;'
        image: nginx
        restart: on-failure
        depends_on:
            - app
        networks: 
            - main
        ports: 
            - "80:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./media:/app/media
            - ./static:/app/static


networks: 
    main:  
        external: true

volumes: 
    static:
        external: true
    
    data:
        external: true
     
    redisdata:
        external: true

