version: '3.9'

services:
    postgres:
        image: postgres
        container_name: postgres_container
        restart: on-failure
        environment: 
            - POSTGRES_DB=movie
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        networks: 
            - main
        ports: 
            - "5432:5432"
        volumes: 
            - postgres_data:/var/lib/postgresql/data 

    redis:
        image: redis
        container_name: redis_container
        ports: 
            - "6379:6379"
        networks: 
            - main

    app:
        container_name: app
        build: .
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && python manage.py initadmin && gunicorn -k gevent config.wsgi:application -b 0.0.0.0:8000"
        restart: on-failure
        depends_on: 
            - postgres
            - redis
        expose: 
            - "8000"
        networks:
            - main
        volumes: 
            - .:/code/
            - ./static:/app/static
            - ./media:/app/media

        
    nginx:
        container_name: nginx
        command: nginx -g 'daemon off;'
        image: nginx
        restart: on-failure
        depends_on:
            - app
        networks: 
            - main
        ports: 
            - "80:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./media:/app/media
            - ./static:/app/static


networks: 
    main:

volumes: 
    static:
    
    postgres_data:
    
