# Generated by Django 3.2.4 on 2021-09-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionuser',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token', verbose_name='Token user'),
            preserve_default=False,
        ),
    ]
