# Generated by Django 3.2.4 on 2021-09-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sessionuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionuser',
            name='token',
        ),
    ]
