# Generated by Django 3.2.4 on 2021-08-06 14:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='category name')),
                ('name_en', models.CharField(max_length=200, verbose_name='category name en')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='your name')),
                ('email', models.EmailField(max_length=254, verbose_name='your email')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='your website')),
                ('message', models.TextField(verbose_name='your messaage')),
            ],
            options={
                'verbose_name': 'message table',
                'verbose_name_plural': 'messages table',
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='serial name')),
                ('title', models.CharField(max_length=200, verbose_name='serial title')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='serial slug')),
                ('description', models.TextField(verbose_name='serial description')),
                ('description_en', models.TextField(verbose_name='serial description en')),
                ('image', models.ImageField(upload_to='serial/awatar/', verbose_name='serial awatar')),
                ('date', models.DateField(verbose_name='serial create date')),
                ('awards', models.CharField(blank=True, max_length=500, null=True, verbose_name='movie awards')),
                ('ratin', models.PositiveIntegerField(blank=True, null=True, verbose_name='serial ratin of 10')),
                ('filmpas', models.FileField(upload_to='serial/pass/', verbose_name='serial preview')),
                ('gener', models.CharField(max_length=250, verbose_name='serial gener')),
                ('gener_en', models.CharField(max_length=250, verbose_name='serial gener en')),
                ('director', models.CharField(blank=True, default='None', max_length=250, null=True, verbose_name='serial director')),
                ('writer', models.CharField(blank=True, default='None', max_length=250, null=True, verbose_name='serial writer')),
                ('stars', models.CharField(blank=True, default='None', max_length=400, null=True, verbose_name='serial stars')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='serial time')),
                ('is_a', models.CharField(default='serial', max_length=6)),
                ('choice', models.CharField(choices=[('iranian', 'iranian'), ('halliwood', 'halliwood'), ('balliwood', 'balliwood'), ('arabic', 'arabic'), ('chaina', 'chaina'), ('turkish', 'turkish')], max_length=15, verbose_name='serial choices')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_serial', to='movie.category', verbose_name='serial category')),
            ],
            options={
                'verbose_name': 'serial table',
                'verbose_name_plural': 'serials table',
            },
        ),
        migrations.CreateModel(
            name='SerialSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.PositiveIntegerField(verbose_name='serial session')),
                ('title', models.CharField(help_text='session one of serial name', max_length=200, verbose_name='serial session title')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='serial session slug')),
                ('subtitle', models.FileField(blank=True, null=True, upload_to='serial/trans/', verbose_name='serial subtitle')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_serial', to='movie.serial')),
            ],
            options={
                'verbose_name': 'serial session table',
                'verbose_name_plural': 'serials session table',
            },
        ),
        migrations.CreateModel(
            name='SerialFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episod', models.PositiveIntegerField(help_text='01', verbose_name='serial episod')),
                ('title', models.CharField(help_text='episod one of session tow serial name', max_length=200, verbose_name='serial title')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='serial slug')),
                ('serial1080', models.FileField(blank=True, null=True, upload_to='serial/1080/', verbose_name='serial quality 1080')),
                ('serial720', models.FileField(blank=True, null=True, upload_to='serial/720', verbose_name='serial quality 720')),
                ('serial480', models.FileField(blank=True, null=True, upload_to='serial/480', verbose_name='serial quality 480')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_film', to='movie.serial', verbose_name='serial relation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_session', to='movie.serialsession', verbose_name='serial film session')),
            ],
            options={
                'verbose_name': 'serial related table',
                'verbose_name_plural': 'serials related table',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=200, verbose_name='serial title')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='serial slug')),
                ('description', models.TextField(verbose_name='serial description')),
                ('description_en', models.TextField(verbose_name='serial description en')),
                ('is_for', models.CharField(choices=[('aerial', 'serial'), ('movie', 'movie')], max_length=15, verbose_name='is for')),
                ('filmpas', models.FileField(blank=True, null=True, upload_to='review/film/', verbose_name='preview')),
                ('object_id', models.PositiveIntegerField()),
                ('choice', models.CharField(max_length=30)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'review table',
                'verbose_name_plural': 'reviews table',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='movie name')),
                ('title', models.CharField(max_length=200, verbose_name='movie title')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='movie slug')),
                ('gener', models.CharField(max_length=250, verbose_name='movie gener')),
                ('gener_en', models.CharField(max_length=250, verbose_name='movie gener en')),
                ('description', models.TextField(verbose_name='movie description')),
                ('description_en', models.TextField(verbose_name='movie description en')),
                ('date', models.DateField(verbose_name='movie date create')),
                ('ratin', models.PositiveIntegerField(blank=True, null=True, verbose_name='movie ratin of 10')),
                ('awards', models.CharField(blank=True, max_length=500, null=True, verbose_name='movie awards')),
                ('image', models.ImageField(upload_to='film/awatar/', verbose_name='movie awatar')),
                ('filmpas', models.FileField(upload_to='film/pass/', verbose_name='movie preview')),
                ('film1080', models.FileField(blank=True, null=True, upload_to='film/1080/', verbose_name='movie quality 1080')),
                ('filme720', models.FileField(blank=True, null=True, upload_to='film/720/', verbose_name='movie quality 720')),
                ('film480', models.FileField(blank=True, null=True, upload_to='film480/', verbose_name='movie quality 1080')),
                ('subtitle', models.FileField(blank=True, null=True, upload_to='trans/', verbose_name='movie subtitle')),
                ('director', models.CharField(blank=True, default='None', max_length=250, null=True, verbose_name='movie director')),
                ('writer', models.CharField(blank=True, default='None', max_length=250, null=True, verbose_name='movie writer')),
                ('stars', models.CharField(blank=True, default='None', max_length=400, null=True, verbose_name='movie stars')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='movie time')),
                ('is_a', models.CharField(default='movie', max_length=5)),
                ('choice', models.CharField(choices=[('iranian', 'iranian'), ('halliwood', 'halliwood'), ('balliwood', 'balliwood'), ('arabic', 'arabic'), ('chaina', 'chaina'), ('turkish', 'turkish')], max_length=15, verbose_name='movie choice')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cat_movie', to='movie.category')),
            ],
            options={
                'verbose_name': 'movie table',
                'verbose_name_plural': 'movies table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_paid', models.DateTimeField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='your phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='user is active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='user is admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
