# Generated by Django 3.2.4 on 2021-08-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_for',
            field=models.CharField(choices=[('serial', 'serial'), ('movie', 'movie')], max_length=15, verbose_name='is for'),
        ),
    ]
