# Generated by Django 3.2.4 on 2021-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
