# Generated by Django 3.2.4 on 2021-09-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagessending',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date sendig email'),
        ),
    ]
