# Generated by Django 3.2.4 on 2021-08-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, verbose_name='email user')),
            ],
            options={
                'verbose_name': 'news letter',
                'verbose_name_plural': 'news letters',
            },
        ),
    ]
