# Generated by Django 3.2.4 on 2021-08-20 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_user_otp_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, verbose_name='email user')),
            ],
            options={
                'verbose_name': 'news letter',
                'verbose_name_plural': 'news letters',
            },
        ),
        migrations.CreateModel(
            name='HistoryPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date paid')),
                ('price', models.PositiveIntegerField(verbose_name='amount of price')),
                ('code', models.CharField(max_length=150, verbose_name='payment code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_paid', to=settings.AUTH_USER_MODEL, verbose_name='history paid')),
            ],
            options={
                'verbose_name': 'history user paid',
                'verbose_name_plural': 'histories user paid',
                'ordering': ('-id',),
            },
        ),
    ]
