# Generated by Django 3.2.4 on 2021-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_historypaid_newsletters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='subject email')),
                ('date', models.DateTimeField(verbose_name='date sendig email')),
                ('messages', models.TextField(verbose_name='message in email')),
            ],
            options={
                'verbose_name': 'messages sending',
                'verbose_name_plural': 'messages sendings',
            },
        ),
    ]
